---
title: "Number of genus (trnL vs ITS2)"
author: "Bailie Wynbelt"
date: "`r Sys.Date()`"
output: github_document
---
Load required packages
```{r}
library(tidyverse)
```

Read in data
```{r}
ITS2 <- read_csv("../outputs/no_millet_vouchers_ITS2.csv")

trnL <- read_csv("../outputs/no_millet_vouchers_trnL.csv")
```

filter reads with a cutoff of 10
```{r}
ITS2 <- ITS2 %>% 
  filter(Reads >= 10)

trnL <- trnL %>% 
  filter(Reads >= 10)

```

count average reads per sampleid
```{r}
total_reads_ITS2 <- ITS2 %>% 
  group_by(SampleID) %>% 
  summarise(total_read = sum(Reads))

avg_reads_ITS2 <- total_reads_ITS2 %>% 
  summarise(avg_reads = mean(total_read))

total_reads_trnL <- trnL %>% 
  group_by(SampleID) %>% 
  summarise(total_read = sum(Reads))

avg_reads_trnL <- total_reads_trnL %>% 
  summarise(avg_reads = mean(total_read))


```

Family, genra, and species counted per ITS2
```{r}
#sort high to low, distinct because it is grouping
counts_family_ITS2 <- ITS2 %>% 
  group_by(Family) %>% 
  count() %>% 
  arrange(desc(n))

counts_genus_ITS2 <- ITS2 %>% 
  group_by(Genus) %>% 
  count() %>% 
  arrange(desc(n))

counts_species_ITS2 <- ITS2 %>% 
  group_by(Species) %>% 
  count() %>% 
  arrange(desc(n))
```

Family, genra, and species counted per trnL
```{r}
#sort high to low
counts_family_trnL <- trnL %>% 
  group_by(Family) %>% 
  count() %>% 
  arrange(desc(n))

counts_genus_trnL <- trnL %>% 
  group_by(Genus) %>% 
  count() %>% 
  arrange(desc(n))

counts_species_trnL <- trnL %>% 
  group_by(Species) %>% 
  count() %>% 
  arrange(desc(n))

```

Unique families 
```{r}
# ITS2: merge the two data frames based on plant family names column
unique_ITS2_families <- merge(counts_family_ITS2, counts_family_trnL, by = "Family", all.x = TRUE)

# ITS2: rename columns
unique_ITS2_families <- unique_ITS2_families %>% 
  rename("ITS2" = n.x,
       "trnL" = n.y) %>% 
  filter(is.na(trnL))

# TRNL: merge the two data frames based on plant family names column
unique_trnL_families <- merge(counts_family_trnL, counts_family_ITS2, by = "Family", all.x = TRUE)

# TRNL: rename columns
unique_trnL_families <- unique_trnL_families %>% 
  rename("trnL" = n.x,
       "ITS2" = n.y) %>% 
  filter(is.na(ITS2))

```

Unique Genera 
```{r}
# ITS2: merge the two data frames based on plant genera names column
unique_ITS2_genus <- merge(counts_genus_ITS2, counts_genus_trnL, by = "Genus", all.x = TRUE)

# ITS2: rename columns
unique_ITS2_genus <- unique_ITS2_genus %>% 
  rename("ITS2" = n.x,
       "trnL" = n.y) %>% 
  filter(is.na(trnL))

# TRNL: merge the two data frames based on plant genera names column
unique_trnL_genus <- merge(counts_genus_trnL, counts_genus_ITS2, by = "Genus", all.x = TRUE)

# TRNL: rename columns
unique_trnL_genus <- unique_trnL_genus %>% 
  rename("trnL" = n.x,
       "ITS2" = n.y) %>% 
  filter(is.na(ITS2))

```

Unique Species
```{r}
# ITS2: merge the two data frames based on plant species names column
unique_ITS2_species <- merge(counts_species_ITS2, counts_species_trnL, by = "Species", all.x = TRUE)

# ITS2: rename columns
unique_ITS2_species <- unique_ITS2_species %>% 
  rename("ITS2" = n.x,
       "trnL" = n.y) %>% 
  filter(is.na(trnL))

# TRNL: merge the two data frames based on plant species names column
unique_trnL_species <- merge(counts_species_trnL, counts_species_ITS2, by = "Species", all.x = TRUE)

# TRNL: rename columns
unique_trnL_species <- unique_trnL_species %>% 
  rename("trnL" = n.x,
       "ITS2" = n.y) %>% 
  filter(is.na(ITS2))

```

See overlap in species (what doesn't overlap)
```{r}
#618 observations originally
#97 overlap - genus
overlap_genus <- count_genus %>% 
  drop_na()

#74 observations originally
#33 overlap - family
overlap_family <- count_family %>% 
  drop_na()

#111 1076 originally
#46 overlap - family
overlap_species <- count_species %>% 
  drop_na()
  
```

