---
title: "Hill Index"
author: "Bailie Wynbelt"
date: "18-04-2023"
output: github_document
---
read packages
```{r}
library(tidyverse)
#install.packages("iNEXT")
library(iNEXT)
```

read data
```{r}
ITS2 <- read_csv("../outputs/no_millet_vouchers_ITS2.csv")

trnL <- read_csv("../outputs/no_millet_vouchers_trnL.csv")
```

10 cutoff 
```{r}
#automatically removes NA's
ITS2 <- ITS2 %>% 
  filter(Reads >= 10) %>% 
  select(SampleID, Genus, Reads)

trnL <- trnL %>% 
  filter(Reads >= 10) %>% 
  select(SampleID, Genus, Reads)

ITS2 <- ITS2 %>% 
  group_by(SampleID, Genus) %>% 
  summarise(Reads = sum(Reads))

trnL <- trnL %>% 
  group_by(SampleID, Genus) %>% 
  summarise(Reads = sum(Reads))

```

shift data frame
```{r}
ITS2_wide <- ITS2 %>% 
  filter(!is.na(Genus)) %>% 
  pivot_wider(names_from = SampleID, values_from = Reads) %>% 
  column_to_rownames("Genus")
    
ITS2_wide <- ITS2_wide %>% 
  replace(is.na(.), 0)

ITS2_wide_2 <- as.matrix(ITS2_wide)

trnL_wide <- trnL %>% 
  filter(!is.na(Genus)) %>% 
  pivot_wider(names_from = SampleID, values_from = Reads) %>% 
  column_to_rownames("Genus")
    
trnL_wide <- trnL_wide %>% 
  replace(is.na(.), 0)

trnL_wide_2 <- as.matrix(trnL_wide)
```

Hill Index - iNext (ITS2)
```{r}
hill_ITS2 <- iNEXT(ITS2_wide_2, datatype = c("abundance"), q = 1)
```

ITS2 Hill Index
```{r}
hill_ITS2$DataInfo
hill_ITS2_numbers <- hill_ITS2$AsyEst
```

Hill Index - iNext (trnl)
```{r}
hill_trnL <- iNEXT(trnL_wide_2, datatype = c("abundance"), q = 1)
```

trnL Hill Index
```{r}
hill_trnL$DataInfo
hill_trnL_numbers <- hill_trnL$AsyEst
```


Hill Index - ITS2
```{r}
#calculates taxonomic diversity for each site (alpha diversity)
#can we consider each sampleID as a unique site, 
# q = 0 (default hill number - can change to get shannon or simpson)
hill_taxa(ITS2, q = 0, MARGIN = 1, base = exp(1))
```

Hill Index - trnL
```{r}
#calculates taxonomic diversity for each site (alpha diversity)
#can we consider each sampleID as a unique site, compairson??
# q = 0 (default hill number - can change to get shannon or simpson)
hill_taxa(trnL, q = 0, MARGIN = 1, base = exp(1))
```
