---
title: "ITS2_diversity"
author: "Bailie Wynbelt"
date: "2023-03-28"
output: html_document
---

#install tidyverse

```{r install packages}
install.packages("vegan")
library(tidyverse)
library(vegan)

```

#load in ITS2 data

```{r read.csv}
reads_WTU_ITS2 <- read_csv("../data/updated_ITS2_reads_WeeTU.csv")
```

###Removing Panicum mili and hirt###

#Remove any rows that have a WTU species value of 122(mili) and 121(hirt)

```{r}
panicum_species <- reads_WTU_ITS2 %>% 
  select(Genus, Species, WTU.species) %>%
  filter(Genus == "Panicum") %>% 
  distinct()

pani_mili_count <- panicum_species %>% 
  filter(Species == "Panicum miliaceum")

pani_hirt_count <- panicum_species %>% 
  filter(Species == "Panicum hirticaule")

no_millet_ITS2 <- reads_WTU_ITS2 %>% 
  filter(WTU.species != "122",
         WTU.species != "121")

```

#Remove data frames that are not needed
```{r}
rm(pani_hirt_count, pani_mili_count, panicum_species)
```

###Remove reads###
```{r}
under_10_reads_ITS2 <- no_millet_ITS2 %>% 
  filter(Reads >= 10)

under_25_reads_ITS2 <- no_millet_ITS2 %>% 
  filter(Reads >= 25)

under_50_reads_ITS2 <- no_millet_ITS2 %>% 
  filter(Reads >= 50)
```

###Diet Diversity###

#Find the sum of total reads
```{r}
under_10_reads_ITS2 <- as.data.frame(under_10_reads_ITS2)

under_10_reads_ITS2$sum_reads<- sum(under_10_reads_ITS2$Reads)

under_25_reads_ITS2$sum_reads<- sum(under_25_reads_ITS2$Reads)

under_50_reads_ITS2$sum_reads<- sum(under_50_reads_ITS2$Reads)
```

#Find the proportion of species 
```{r}
under_10_reads_ITS2 <- under_10_reads_ITS2 %>% 
  group_by(SampleID) %>% 
  mutate(pI = (Reads/sum_reads))

under_25_reads_ITS2 <- under_25_reads_ITS2 %>% 
  group_by(SampleID) %>% 
  mutate(pI = (Reads/sum_reads))

under_50_reads_ITS2 <- under_50_reads_ITS2 %>% 
  group_by(SampleID) %>% 
  mutate(pI = (Reads/sum_reads))
```

#Calculate the diversity index
```{r}
under_10_reads_ITS2 <- under_10_reads_ITS2 %>% 
  mutate(diversity_index = -sum(pI*log(pI))) 

under_25_reads_ITS2 <- under_25_reads_ITS2 %>% 
  mutate(diversity_index = -sum(pI*log(pI)))

under_50_reads_ITS2 <- under_50_reads_ITS2 %>% 
  mutate(diversity_index = -sum(pI*log(pI)))

```

#group by species
```{r}
diversity_under_10 <- under_10_reads_ITS2 %>% 
  select(SampleID, sum_reads, pI, diversity_index) %>% 
  distinct(SampleID, .keep_all = TRUE)

diversity_under_25 <- under_25_reads_ITS2 %>% 
  select(SampleID, sum_reads, pI, diversity_index) %>% 
  distinct(SampleID, .keep_all = TRUE)

diversity_under_50 <- under_50_reads_ITS2 %>% 
  select(SampleID, sum_reads, pI, diversity_index) %>% 
  distinct(SampleID, .keep_all = TRUE)
```

#Look at differences in cut-offs
```{r}

```