---
title: "trnL_diversity_genus"
author: "Bailie Wynbelt"
date: "2023-03-29"
output: github_document
---

#install tidyverse
```{r install packages}
library(tidyverse)
```

#load in ITS2 data
```{r read.csv}
reads_WTU_trnL <- read_csv("../data/updated_trnL_reads_WeeTU.csv")
```
###Group by Genus###
```{r}
genus_group_trnL <- reads_WTU_trnL %>% 
  group_by(SampleID, Genus) %>% 
  summarise(Reads = sum(Reads))
```

###Remove reads###
```{r}
under_10_reads_trnL <- genus_group_trnL %>% 
  filter(Reads >= 10)

under_25_reads_trnL <- genus_group_trnL %>% 
  filter(Reads >= 25)

under_50_reads_trnL <- genus_group_trnL %>% 
  filter(Reads >= 50)
```

###Diet Diversity###

#Find the sum of total reads
```{r}
under_10_reads_trnL <- under_10_reads_trnL %>% 
  group_by(SampleID) %>% 
  mutate(sum_reads_ID = sum(Reads))

under_25_reads_trnL <- under_25_reads_trnL %>% 
  group_by(SampleID) %>% 
  mutate(sum_reads_ID = sum(Reads))

under_50_reads_trnL <- under_50_reads_trnL %>% 
  group_by(SampleID) %>% 
  mutate(sum_reads_ID = sum(Reads))
```

#Find the proportion of species 
```{r}
under_10_reads_trnL <- under_10_reads_trnL %>% 
  group_by(SampleID) %>% 
  mutate(pI = (Reads/sum_reads_ID))

under_25_reads_trnL <- under_25_reads_trnL %>% 
  group_by(SampleID) %>% 
  mutate(pI = (Reads/sum_reads_ID))

under_50_reads_trnL <- under_50_reads_trnL %>% 
  group_by(SampleID) %>% 
  mutate(pI = (Reads/sum_reads_ID))
```

#Calculate the diversity index
```{r}
under_10_reads_trnL <- under_10_reads_trnL %>% 
  mutate(diversity_index = -sum(pI*log(pI))) 

under_25_reads_trnL <- under_25_reads_trnL %>% 
  mutate(diversity_index = -sum(pI*log(pI)))

under_50_reads_trnL <- under_50_reads_trnL %>% 
  mutate(diversity_index = -sum(pI*log(pI)))

```

#group by species
```{r}
diversity_under_10 <- under_10_reads_trnL %>% 
  select(SampleID, sum_reads_ID, pI, diversity_index) %>% 
  distinct(SampleID, .keep_all = TRUE)

diversity_under_25 <- under_25_reads_trnL %>% 
  select(SampleID, sum_reads_ID, pI, diversity_index) %>% 
  distinct(SampleID, .keep_all = TRUE)

diversity_under_50 <- under_50_reads_trnL %>% 
  select(SampleID, sum_reads_ID, pI, diversity_index) %>% 
  distinct(SampleID, .keep_all = TRUE)
```

### Visualize ###

#Join cutoff data frames
```{r}
joined_diversity <- diversity_under_10 %>% 
  left_join(diversity_under_25, by = "SampleID") %>% 
  rename(diversity_index_10 = diversity_index.x,
         diversity_index_25 = diversity_index.y) %>% 
  select(-c(sum_reads_ID.x, pI.x, sum_reads_ID.y, pI.y))

joined_diversity <- joined_diversity %>% 
  left_join(diversity_under_50, by = "SampleID") %>% 
  rename(diversity_index_50 = diversity_index) %>% 
  select(-c(pI, sum_reads_ID))

write_csv(joined_diversity, file = "../outputs/diversity_by_genus_trnL")

```

#Join cutoff data frames 2.0
```{r}
#help im stuck
```

#Look at ggplot
```{r}
ggplot(data = joined_diversity, aes(x = diversity_index, colors = cutoff)) +
  geom_histogram()
```

#Look at differences in cut-offs
```{r}
#why isnt this working. help.
sum_diversity <- joined_diversity %>% 
  summarise(sum_diversity_10 = mean(diversity_index_10),
            sum_diversity_25 = mean(diversity_index_25, na.rm = TRUE),
            sum_diversity_50 = mean(diversity_index_50, na.rm = TRUE))

```

#Run stats - is there a statistical differenece
```{r}

```